spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://second-life.chkgusieka1x.ap-northeast-2.rds.amazonaws.com:3306/second?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: secondlife

  profiles:
    active: local

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    #        show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 20

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

logging.level:
  root: INFO
  org.hibernate.SQL: debug
  org.springframework.transaction.interceptor: TRACE

server:
  servlet:
    session:
      timeout: 30m


gpt:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
    system: " 반말로, 100자내외로 얘기해줘. "